server:
  port: 8712
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/db-cdc
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher